services:
    kunstmaan_admin.consolelogger.listener:
        class: Kunstmaan\AdminBundle\EventListener\ConsoleExceptionListener
        arguments:
            logger: "@logger"
        tags:
            - { name: kernel.event_listener, event: console.exception }
